---
- name: Playbook for Downloading from link
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks:
    - name: Download package
      get_url:
        url: "{{ url }}"
        dest: /tmp 